#!/bin/bash

#---------------------------------------------------
# Allclean script for building3D_blast case
#---------------------------------------------------

# Remove log files
rm -f log.*

# Remove processor directories
rm -rf processor*

# Remove mesh directories
rm -rf constant/polyMesh

# Remove time directories (but preserve 0/)
rm -rf [1-9]*

#---------------------------------------------------
# End of Allclean script
#---------------------------------------------------