#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication setFields
runApplication $(getApplication)